### ISSUE TITLE
WARN: Starting local-mode server in deprecated socket mode (CHEF-18)

### ISSUE THREAD

**Issue by EugenMayer** [higanworks/knife-zero#115]
When using knife zero nowdays i get

```
WARN: Starting local-mode server in deprecated socket mode (CHEF-18) at /opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/chef-13.2.20/bin/knife:25:in `<top (required)>'.
```

Are there any plans or alternatives to the socket mode?

**Comment by sawanoboly** [comment]
sorry for delay. 

If chef-zero completely removes the HTTP interface and there is no option to use it, maintaining knife-zero will be difficult. As of now there are no plans at all.

**Comment by sawanoboly** [comment]
However, since the socketless server is also based on Rack interface, it is possible to implement TCP listeners with knife-zero.
It depends on the motivation of me or the contributors.

**Comment by EugenMayer** [comment]
I guess there is still some time until those depreciation is going to be a limitation but I guess it's good to have this issue as a possibility to channel the future effort or at least have a clear communication that this will not be implemented and people can look on how they can work around this... Or contribute :)

Thank you for giving some feedback on this!

**Comment by limitusus** [comment]
Chef local-mode is announced to be removed at Chef14, expected to be released on 2 April 2018.
It looks the time to migrate to socketless server.

**Comment by sawanoboly** [comment]
Thanks @limitusus ,

If tcp socket mode is deleted, this test will fail, so we will consider if we can deal with it later.

https://circleci.com/gh/higanworks/knife-zero/tree/integration_testedge

**Comment by darkn3rd** [comment]
Actually, they are saying just add `--listen` for services that need it, when running `chef-client -z` on the remote system.  If I am reading this correctly, the fix is easy.

They had the same problem with chef provision (aka chef metal) that bootstraps systems using a similar mechanism.

**Comment by sawanoboly** [comment]
@darkn3rd  Thanks, and don't worry about it.

knife-zero already turns on `--listen` option by default since `v1.18.1`. https://github.com/higanworks/knife-zero/blob/master/CHANGELOG.md

However, Chef's RFC could be interpret the `--listen` option someday to disappear. If it disappears then I will consider about it.

**Comment by EugenMayer** [comment]
@sawanoboly so this issue is fixed already? (1.18.1) ?

**Comment by sawanoboly** [comment]
@EugenMayer 

We have not solved the fundamental concern that the core might delete the function, and the WARN message will continue to be displayed.

However, it does not need to take any action for a while.

**Comment by EugenMayer** [comment]
thanks for the clarification!

**Comment by sawanoboly** [comment]
http://goiardi.gl

**Comment by sawanoboly** [comment]
If Chef-Zero's local TCP listening is abolished, maybe we should introduce http://goiardi.gl.
