### ISSUE TITLE
sudo option behavior? of 1.1.6 both bootstrap and chef_client

### ISSUE THREAD

**Issue by sawanoboly** [higanworks/knife-zero#22]
T/O

**Comment by patcon** [comment]
I think you might be asking whether knife[:use_sudo] should be working in both bootstrap and chef_client commands. If so, I'm seeing inconsistent behaviour as well.

Thinking perhaps it has to do with this during "chef_client" command:
https://github.com/higanworks/knife-zero/blob/e3472825b310ee22fdcc452751a708ab09b9636b/lib/chef/knife/zero_chef_client.rb#L44-L45

**Comment by sawanoboly** [comment]
Maybe this issue has been fixed at about 1.3〜1.5. Thanks.

**Comment by patcon** [comment]
Nope, it's actually still an issue :/

https://gist.github.com/patcon/419db260565e73577186

**Comment by sawanoboly** [comment]
OK, I have remembered what is problem and why I created it.

**Comment by sawanoboly** [comment]
I found that remote command was built before loading knife.rb...
